### ISSUE TITLE
Setup project structure

### ISSUE THREAD

**Issue by Wertros** [TheBrothersCode/warn-me#5]
Create initial project structure.

## Definiton of done:

- Maven project with required base dependencies in `pom.xml`
- valid `.gitignore`
- Very simple spring boot class with `main` method
- Integration test that passes

**Comment by Wertros** [comment]
4h

**Comment by TheDariusz** [comment]
* maven failsafe plugin (integration tests - końcówka IT) 
* maven surefire plugin (unit tests)

mvn clean verify - odpala testy integ.

**Comment by Wertros** [comment]
done
